include:
   - component: $CI_SERVER_FQDN/quiqqer/stabilization/ci-cd-components/php-tooling-bundle/php-tooling-bundle@1
    inputs:
        php-81: false

.prepare-image:
  before_script:
    # Install convert (imagemagick) and chrome (for chrome-headless)
    - sudo apt-get update
    - sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -qO /tmp/google-chrome-stable_current_amd64.deb
    - sudo apt-get install -yq /tmp/google-chrome-stable_current_amd64.deb
    - sudo apt-get install -yq imagemagick
    # Remove incompatible package (is part of default QUIQQER installation template)
    - cd /var/www/html; ./console composer remove quiqqer/gdpr

phpstan:
  extends: .prepare-image

phpunit-php8.3:
  extends: .prepare-image

phpunit-php8.4:
  extends: .prepare-image

phpunit-php8.5:
  extends: .prepare-image
